spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      initialization-fail-timeout: 60000
      connection-timeout: 30000
  sql:
    init:
      mode: never  # init sql is handled in docker-compose